insert into public.sprawnosci (nazwa, kategoria) values
  ('Pocztowiec', 'Służba'),
  ('Sanitariusz', 'Służba'),
  ('Złota Rączka', 'Służba'),
  ('Przewodnik', 'Służba'),
  ('Kucharz', 'Służba'),
  ('Krawiec', 'Służba'),
  ('Sportowiec', 'Zręczność'),
  ('Rowerzysta', 'Zręczność'),
  ('Wędkarz', 'Zręczność'),
  ('Pływak', 'Zręczność'),
  ('Dobry Gracz', 'Zręczność'),
  ('Znawca Ewangelii', 'Wiara'),
  ('Liturgista', 'Wiara'),
  ('Ministrant', 'Wiara'),
  ('Pielgrzym', 'Wiara'),
  ('Znawca Świętych', 'Wiara'),
  ('Geograf', 'Wiedza'),
  ('Mistrz Ekspresji', 'Wiedza'),
  ('Reporter', 'Wiedza'),
  ('Agent', 'Wiedza'),
  ('Wilczek Europy', 'Wiedza'),
  ('Astronom', 'Wiedza'),
  ('Obieżyświat', 'Wiedza'),
  ('Elektryk', 'Zmysł praktyczny'),
  ('Obozowicz', 'Zmysł praktyczny'),
  ('Fotograf', 'Zmysł praktyczny'),
  ('Muzykant', 'Zmysł praktyczny'),
  ('Ogrodnik', 'Zmysł praktyczny'),
  ('Artysta', 'Zmysł praktyczny');
